

import java.sql.SQLException;
import java.util.ArrayList;

public class DataBaseConstructor extends DataCommands{
	 ///////////////////////////////
	//TODO create array of strings for each table and loop through them using each as a SQL statement.
	//need to cut down on redundancy.
	///////////////////////////////
	static ArrayList<String> sqlQueries = new ArrayList<String>();
	private static String createTable;
	protected static String setTableToCreate(String command){
		return createTable = command;
	}
	static ArrayList<String> practiceData = new ArrayList<String>();
	private static String dataPoint;
	protected static String setDataPoint(String data){
		return dataPoint = data;
	}
	
	protected static void assignTables(){
		setTableToCreate( 
				"CREATE TABLE USERS ("
				+ "userID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "
				+ "userName varchar(20) not null, "
				+ "userAuth integer not null with DEFAULT 1, "
				+ "userPass varchar(20) not null, "
				+ "userPhone varchar(10) not null,"
				+ "userEmail varchar(20),"
				+ "Primary key(userID)"
				+ ")");
		sqlQueries.add(createTable);
		setTableToCreate(
				"CREATE TABLE COSIGNER"
				+ "("
				//big thanks to Denise Michelle deBando on programming Journal-dmdb.blogspot.com
				+ "cosignerID INTEGER NOT NULL GENERATED BY DEFAULT,"
				//end of used code
				+ "cosignorName varchar(20) NOT NULL,"
				+ "cosignorPhone varchar(20) NOT NULL,"
				+ "Primary key(cosignerID)"
				+ ")");
		sqlQueries.add(createTable);
		setTableToCreate(
				"CREATE TABLE RECORDS"
				+ "("
				+ "musicID INTEGER NOT NULL GENERATED BY DEFAULT,"
				+ "title varchar(20) NOT NULL,"
				+ "artist VARCHAR(20) NOT NULL,"
				+ "price float NOT NULL,"
				+ "dateAdded TIMESTAMP,"
				+ "cosignorID INT REFERENCES COSIGNOR(cosignorID),"
				+ "Primary Key (musicID)"
				+ ")");
		sqlQueries.add(createTable);
		setTableToCreate(
				"CREATE TABLE SALES"
				+ "("
				+ "salesID INTEGER NOT NULL GENERATED BY DEFAULT,"
				+ "date DATE,"
				+ "musicID INT REFERENCES RECORDS(musicID),"
				+ "userID INT REFERENCES USERS(userID),"
				+ "Primary key(salesID)"
				+ ")");
		sqlQueries.add(createTable);
	}
	
	public static void createDataTables(){
		try {
			DataConnect("root","p4ssw0rd");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		for(String i: sqlQueries){
			try{
				sqlCom = conn.createStatement();
				Object Table = sqlCom.executeQuery(i);
			}catch(SQLException e){
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			try{
				sqlCom.close();
			}catch(SQLException e){
				e.printStackTrace();
			}
		}
	}
	
	public static void populate(String name,ArrayList<String> data){
		try{
			DataConnect("root","p4ssw0rd");
		}catch(ClassNotFoundException e){
			e.printStackTrace();
		}
		cosignorData();
		for(String i: practiceData){
			try{
				sqlCom = conn.createStatement();
				Object Table = sqlCom.executeQuery(
						"INSERT INTO "
						+ name
						+" VALUES "
						+ "("
						+ i
						+ ")"
						);
			}catch(SQLException e){
				e.printStackTrace();
			}
		}
	}
	
	public static void cosignorData(){
		practiceData = new ArrayList<String>();
		setDataPoint("Sun Records,012-345-6789");
		practiceData.add(dataPoint);
		setDataPoint("Lion Records,987-654-3210");
		practiceData.add(dataPoint);
	}
	
	public static void MusicData(){
		
	}
}
